// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PeerList.proto

package network.messageTypes;

public final class PeerProtos {
  private PeerProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PeerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Peer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required bytes IP = 1;</code>
     */
    boolean hasIP();
    /**
     * <code>required bytes IP = 1;</code>
     */
    com.google.protobuf.ByteString getIP();

    /**
     * <code>required uint32 port = 2;</code>
     */
    boolean hasPort();
    /**
     * <code>required uint32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>required bytes id = 3;</code>
     */
    boolean hasId();
    /**
     * <code>required bytes id = 3;</code>
     */
    com.google.protobuf.ByteString getId();
  }
  /**
   * Protobuf type {@code Peer}
   */
  public  static final class Peer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Peer)
      PeerOrBuilder {
    // Use Peer.newBuilder() to construct.
    private Peer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Peer() {
      iP_ = com.google.protobuf.ByteString.EMPTY;
      port_ = 0;
      id_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Peer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              iP_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              port_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              id_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.messageTypes.PeerProtos.internal_static_Peer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.messageTypes.PeerProtos.internal_static_Peer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.messageTypes.PeerProtos.Peer.class, network.messageTypes.PeerProtos.Peer.Builder.class);
    }

    private int bitField0_;
    public static final int IP_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString iP_;
    /**
     * <code>required bytes IP = 1;</code>
     */
    public boolean hasIP() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes IP = 1;</code>
     */
    public com.google.protobuf.ByteString getIP() {
      return iP_;
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required uint32 port = 2;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString id_;
    /**
     * <code>required bytes id = 3;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes id = 3;</code>
     */
    public com.google.protobuf.ByteString getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIP()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, iP_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, id_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, iP_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof network.messageTypes.PeerProtos.Peer)) {
        return super.equals(obj);
      }
      network.messageTypes.PeerProtos.Peer other = (network.messageTypes.PeerProtos.Peer) obj;

      boolean result = true;
      result = result && (hasIP() == other.hasIP());
      if (hasIP()) {
        result = result && getIP()
            .equals(other.getIP());
      }
      result = result && (hasPort() == other.hasPort());
      if (hasPort()) {
        result = result && (getPort()
            == other.getPort());
      }
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasIP()) {
        hash = (37 * hash) + IP_FIELD_NUMBER;
        hash = (53 * hash) + getIP().hashCode();
      }
      if (hasPort()) {
        hash = (37 * hash) + PORT_FIELD_NUMBER;
        hash = (53 * hash) + getPort();
      }
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static network.messageTypes.PeerProtos.Peer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.messageTypes.PeerProtos.Peer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.messageTypes.PeerProtos.Peer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.messageTypes.PeerProtos.Peer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.messageTypes.PeerProtos.Peer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static network.messageTypes.PeerProtos.Peer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static network.messageTypes.PeerProtos.Peer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static network.messageTypes.PeerProtos.Peer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static network.messageTypes.PeerProtos.Peer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static network.messageTypes.PeerProtos.Peer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.messageTypes.PeerProtos.Peer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Peer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Peer)
        network.messageTypes.PeerProtos.PeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.messageTypes.PeerProtos.internal_static_Peer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.messageTypes.PeerProtos.internal_static_Peer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.messageTypes.PeerProtos.Peer.class, network.messageTypes.PeerProtos.Peer.Builder.class);
      }

      // Construct using network.messageTypes.PeerProtos.Peer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        iP_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.messageTypes.PeerProtos.internal_static_Peer_descriptor;
      }

      public network.messageTypes.PeerProtos.Peer getDefaultInstanceForType() {
        return network.messageTypes.PeerProtos.Peer.getDefaultInstance();
      }

      public network.messageTypes.PeerProtos.Peer build() {
        network.messageTypes.PeerProtos.Peer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.messageTypes.PeerProtos.Peer buildPartial() {
        network.messageTypes.PeerProtos.Peer result = new network.messageTypes.PeerProtos.Peer(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.iP_ = iP_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.messageTypes.PeerProtos.Peer) {
          return mergeFrom((network.messageTypes.PeerProtos.Peer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.messageTypes.PeerProtos.Peer other) {
        if (other == network.messageTypes.PeerProtos.Peer.getDefaultInstance()) return this;
        if (other.hasIP()) {
          setIP(other.getIP());
        }
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIP()) {
          return false;
        }
        if (!hasPort()) {
          return false;
        }
        if (!hasId()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.messageTypes.PeerProtos.Peer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.messageTypes.PeerProtos.Peer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString iP_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes IP = 1;</code>
       */
      public boolean hasIP() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required bytes IP = 1;</code>
       */
      public com.google.protobuf.ByteString getIP() {
        return iP_;
      }
      /**
       * <code>required bytes IP = 1;</code>
       */
      public Builder setIP(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        iP_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes IP = 1;</code>
       */
      public Builder clearIP() {
        bitField0_ = (bitField0_ & ~0x00000001);
        iP_ = getDefaultInstance().getIP();
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>required uint32 port = 2;</code>
       */
      public boolean hasPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public Builder setPort(int value) {
        bitField0_ |= 0x00000002;
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        port_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString id_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes id = 3;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes id = 3;</code>
       */
      public com.google.protobuf.ByteString getId() {
        return id_;
      }
      /**
       * <code>required bytes id = 3;</code>
       */
      public Builder setId(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes id = 3;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Peer)
    }

    // @@protoc_insertion_point(class_scope:Peer)
    private static final network.messageTypes.PeerProtos.Peer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.messageTypes.PeerProtos.Peer();
    }

    public static network.messageTypes.PeerProtos.Peer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Peer>
        PARSER = new com.google.protobuf.AbstractParser<Peer>() {
      public Peer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Peer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Peer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Peer> getParserForType() {
      return PARSER;
    }

    public network.messageTypes.PeerProtos.Peer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PeerListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PeerList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    java.util.List<network.messageTypes.PeerProtos.Peer> 
        getPeersList();
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    network.messageTypes.PeerProtos.Peer getPeers(int index);
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    int getPeersCount();
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    java.util.List<? extends network.messageTypes.PeerProtos.PeerOrBuilder> 
        getPeersOrBuilderList();
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    network.messageTypes.PeerProtos.PeerOrBuilder getPeersOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code PeerList}
   */
  public  static final class PeerList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PeerList)
      PeerListOrBuilder {
    // Use PeerList.newBuilder() to construct.
    private PeerList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PeerList() {
      peers_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PeerList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                peers_ = new java.util.ArrayList<network.messageTypes.PeerProtos.Peer>();
                mutable_bitField0_ |= 0x00000001;
              }
              peers_.add(
                  input.readMessage(network.messageTypes.PeerProtos.Peer.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          peers_ = java.util.Collections.unmodifiableList(peers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return network.messageTypes.PeerProtos.internal_static_PeerList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return network.messageTypes.PeerProtos.internal_static_PeerList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              network.messageTypes.PeerProtos.PeerList.class, network.messageTypes.PeerProtos.PeerList.Builder.class);
    }

    public static final int PEERS_FIELD_NUMBER = 1;
    private java.util.List<network.messageTypes.PeerProtos.Peer> peers_;
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    public java.util.List<network.messageTypes.PeerProtos.Peer> getPeersList() {
      return peers_;
    }
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    public java.util.List<? extends network.messageTypes.PeerProtos.PeerOrBuilder> 
        getPeersOrBuilderList() {
      return peers_;
    }
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    public int getPeersCount() {
      return peers_.size();
    }
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    public network.messageTypes.PeerProtos.Peer getPeers(int index) {
      return peers_.get(index);
    }
    /**
     * <code>repeated .Peer peers = 1;</code>
     */
    public network.messageTypes.PeerProtos.PeerOrBuilder getPeersOrBuilder(
        int index) {
      return peers_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getPeersCount(); i++) {
        if (!getPeers(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < peers_.size(); i++) {
        output.writeMessage(1, peers_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < peers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, peers_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof network.messageTypes.PeerProtos.PeerList)) {
        return super.equals(obj);
      }
      network.messageTypes.PeerProtos.PeerList other = (network.messageTypes.PeerProtos.PeerList) obj;

      boolean result = true;
      result = result && getPeersList()
          .equals(other.getPeersList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getPeersCount() > 0) {
        hash = (37 * hash) + PEERS_FIELD_NUMBER;
        hash = (53 * hash) + getPeersList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static network.messageTypes.PeerProtos.PeerList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.messageTypes.PeerProtos.PeerList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.messageTypes.PeerProtos.PeerList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static network.messageTypes.PeerProtos.PeerList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static network.messageTypes.PeerProtos.PeerList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static network.messageTypes.PeerProtos.PeerList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static network.messageTypes.PeerProtos.PeerList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static network.messageTypes.PeerProtos.PeerList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static network.messageTypes.PeerProtos.PeerList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static network.messageTypes.PeerProtos.PeerList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(network.messageTypes.PeerProtos.PeerList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PeerList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PeerList)
        network.messageTypes.PeerProtos.PeerListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return network.messageTypes.PeerProtos.internal_static_PeerList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return network.messageTypes.PeerProtos.internal_static_PeerList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                network.messageTypes.PeerProtos.PeerList.class, network.messageTypes.PeerProtos.PeerList.Builder.class);
      }

      // Construct using network.messageTypes.PeerProtos.PeerList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPeersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (peersBuilder_ == null) {
          peers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          peersBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return network.messageTypes.PeerProtos.internal_static_PeerList_descriptor;
      }

      public network.messageTypes.PeerProtos.PeerList getDefaultInstanceForType() {
        return network.messageTypes.PeerProtos.PeerList.getDefaultInstance();
      }

      public network.messageTypes.PeerProtos.PeerList build() {
        network.messageTypes.PeerProtos.PeerList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public network.messageTypes.PeerProtos.PeerList buildPartial() {
        network.messageTypes.PeerProtos.PeerList result = new network.messageTypes.PeerProtos.PeerList(this);
        int from_bitField0_ = bitField0_;
        if (peersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            peers_ = java.util.Collections.unmodifiableList(peers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.peers_ = peers_;
        } else {
          result.peers_ = peersBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof network.messageTypes.PeerProtos.PeerList) {
          return mergeFrom((network.messageTypes.PeerProtos.PeerList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(network.messageTypes.PeerProtos.PeerList other) {
        if (other == network.messageTypes.PeerProtos.PeerList.getDefaultInstance()) return this;
        if (peersBuilder_ == null) {
          if (!other.peers_.isEmpty()) {
            if (peers_.isEmpty()) {
              peers_ = other.peers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePeersIsMutable();
              peers_.addAll(other.peers_);
            }
            onChanged();
          }
        } else {
          if (!other.peers_.isEmpty()) {
            if (peersBuilder_.isEmpty()) {
              peersBuilder_.dispose();
              peersBuilder_ = null;
              peers_ = other.peers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              peersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPeersFieldBuilder() : null;
            } else {
              peersBuilder_.addAllMessages(other.peers_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getPeersCount(); i++) {
          if (!getPeers(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        network.messageTypes.PeerProtos.PeerList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (network.messageTypes.PeerProtos.PeerList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<network.messageTypes.PeerProtos.Peer> peers_ =
        java.util.Collections.emptyList();
      private void ensurePeersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          peers_ = new java.util.ArrayList<network.messageTypes.PeerProtos.Peer>(peers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          network.messageTypes.PeerProtos.Peer, network.messageTypes.PeerProtos.Peer.Builder, network.messageTypes.PeerProtos.PeerOrBuilder> peersBuilder_;

      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public java.util.List<network.messageTypes.PeerProtos.Peer> getPeersList() {
        if (peersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(peers_);
        } else {
          return peersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public int getPeersCount() {
        if (peersBuilder_ == null) {
          return peers_.size();
        } else {
          return peersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public network.messageTypes.PeerProtos.Peer getPeers(int index) {
        if (peersBuilder_ == null) {
          return peers_.get(index);
        } else {
          return peersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder setPeers(
          int index, network.messageTypes.PeerProtos.Peer value) {
        if (peersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeersIsMutable();
          peers_.set(index, value);
          onChanged();
        } else {
          peersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder setPeers(
          int index, network.messageTypes.PeerProtos.Peer.Builder builderForValue) {
        if (peersBuilder_ == null) {
          ensurePeersIsMutable();
          peers_.set(index, builderForValue.build());
          onChanged();
        } else {
          peersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder addPeers(network.messageTypes.PeerProtos.Peer value) {
        if (peersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeersIsMutable();
          peers_.add(value);
          onChanged();
        } else {
          peersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder addPeers(
          int index, network.messageTypes.PeerProtos.Peer value) {
        if (peersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePeersIsMutable();
          peers_.add(index, value);
          onChanged();
        } else {
          peersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder addPeers(
          network.messageTypes.PeerProtos.Peer.Builder builderForValue) {
        if (peersBuilder_ == null) {
          ensurePeersIsMutable();
          peers_.add(builderForValue.build());
          onChanged();
        } else {
          peersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder addPeers(
          int index, network.messageTypes.PeerProtos.Peer.Builder builderForValue) {
        if (peersBuilder_ == null) {
          ensurePeersIsMutable();
          peers_.add(index, builderForValue.build());
          onChanged();
        } else {
          peersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder addAllPeers(
          java.lang.Iterable<? extends network.messageTypes.PeerProtos.Peer> values) {
        if (peersBuilder_ == null) {
          ensurePeersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, peers_);
          onChanged();
        } else {
          peersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder clearPeers() {
        if (peersBuilder_ == null) {
          peers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          peersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public Builder removePeers(int index) {
        if (peersBuilder_ == null) {
          ensurePeersIsMutable();
          peers_.remove(index);
          onChanged();
        } else {
          peersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public network.messageTypes.PeerProtos.Peer.Builder getPeersBuilder(
          int index) {
        return getPeersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public network.messageTypes.PeerProtos.PeerOrBuilder getPeersOrBuilder(
          int index) {
        if (peersBuilder_ == null) {
          return peers_.get(index);  } else {
          return peersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public java.util.List<? extends network.messageTypes.PeerProtos.PeerOrBuilder> 
           getPeersOrBuilderList() {
        if (peersBuilder_ != null) {
          return peersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(peers_);
        }
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public network.messageTypes.PeerProtos.Peer.Builder addPeersBuilder() {
        return getPeersFieldBuilder().addBuilder(
            network.messageTypes.PeerProtos.Peer.getDefaultInstance());
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public network.messageTypes.PeerProtos.Peer.Builder addPeersBuilder(
          int index) {
        return getPeersFieldBuilder().addBuilder(
            index, network.messageTypes.PeerProtos.Peer.getDefaultInstance());
      }
      /**
       * <code>repeated .Peer peers = 1;</code>
       */
      public java.util.List<network.messageTypes.PeerProtos.Peer.Builder> 
           getPeersBuilderList() {
        return getPeersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          network.messageTypes.PeerProtos.Peer, network.messageTypes.PeerProtos.Peer.Builder, network.messageTypes.PeerProtos.PeerOrBuilder> 
          getPeersFieldBuilder() {
        if (peersBuilder_ == null) {
          peersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              network.messageTypes.PeerProtos.Peer, network.messageTypes.PeerProtos.Peer.Builder, network.messageTypes.PeerProtos.PeerOrBuilder>(
                  peers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          peers_ = null;
        }
        return peersBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PeerList)
    }

    // @@protoc_insertion_point(class_scope:PeerList)
    private static final network.messageTypes.PeerProtos.PeerList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new network.messageTypes.PeerProtos.PeerList();
    }

    public static network.messageTypes.PeerProtos.PeerList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PeerList>
        PARSER = new com.google.protobuf.AbstractParser<PeerList>() {
      public PeerList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PeerList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PeerList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PeerList> getParserForType() {
      return PARSER;
    }

    public network.messageTypes.PeerProtos.PeerList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Peer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Peer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PeerList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PeerList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016PeerList.proto\",\n\004Peer\022\n\n\002IP\030\001 \002(\014\022\014\n\004" +
      "port\030\002 \002(\r\022\n\n\002id\030\003 \002(\014\" \n\010PeerList\022\024\n\005pe" +
      "ers\030\001 \003(\0132\005.PeerB\"\n\024network.messageTypes" +
      "B\nPeerProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Peer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Peer_descriptor,
        new java.lang.String[] { "IP", "Port", "Id", });
    internal_static_PeerList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PeerList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PeerList_descriptor,
        new java.lang.String[] { "Peers", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
